name: build exe

on:
  workflow_dispatch:

jobs:
  pack:
    name: bundling & packing
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Node.js environment
      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.0

      # Install dependencies
      - name: 'Install Dependencies'
        run: npm install

      # Bundle the project with esbuild
      - name: 'Bundling with esbuild'
        run: npx esbuild index.js --bundle --platform=node --external:./xhr-sync-worker.js --external:canvas --outfile=dist/index.js

      # Package the app with pkg
      - name: 'Packaging with pkg'
        run: npx pkg --compress GZip -t node14-win dist/index.js

      # Set up Git user
      - name: 'Set up Git user'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Fetch tags to find the latest version
      - name: 'Fetch tags'
        run: git fetch --tags

      # Get the latest tag
      - name: 'Get latest tag'
        id: get_tag
        run: |
          VERSION=$(git tag -l | sort -V | tail -n 1
