name: build exe
on:
  workflow_dispatch:
jobs:
  pack:
    name: bundling & packing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.0
      - name: 'Install Dependencies'
        run: npm install
      - name: 'Bundling with esbuild'
        run: npx esbuild index.js --bundle --platform=node --external:canvas --outfile=dist/index.js
      - name: 'Packaging with pkg'
        run: npx pkg --compress GZip -t node14-win dist/index.js
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
         fallback: 1.0.0
      - name: 'Get next version'
        id: monoversion
        uses: "WyriHaximus/github-action-next-release-version@1.0.0"
        with:
         version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Release'
        uses: actions/create-release@v1
        id: create_release
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
         draft: false
         prerelease: false
         tag_name: ${{ steps.monoversion.outputs.version }}
         release_name: Release ${{ steps.monoversion.outputs.version}}
      - name: 'Upload Release'
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./index.exe
         asset_name: index.exe
         asset_content_type: application/exe
#       - name: Upload server release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: '**/*.exe'
#           file_glob: true
#           tag: ${{ github.ref }}
#           overwrite: true
#       - uses: actions/upload-artifact@v2
#         with:
#           name: distributables
#           path: dist/*
#           if-no-files-found: error
#       - uses: actions/upload-artifact@v2
#         with:
#           name: executeable
#           path: '**/*.exe'
#           if-no-files-found: error
#   publish:
#     name: Publish a release
#     runs-on: "ubuntu-18.04"
#     needs:
#       - pack
#     steps:
#       - name: Get our distributables
#         uses: actions/download-artifact@v2
#         with:
#           name: executeable
#           path: exe

      
