name: build exe
on:
  workflow_dispatch:
jobs:
  pack:
    name: bundling & packing
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.0
      - name: Install Dependencies
        run: npm install
      - name: Bundling with esbuild
        run: npx esbuild index.js --bundle --platform=node --external:canvas --outfile=dist/index.js
      - name: Packaging with pkg
        run: npx pkg --compress GZip -t node14-win dist/index.js
      - uses: actions/upload-artifact@v2
        with:
          name: distributables
          path: dist/*
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: executeable
          path: '**/*.exe'
          if-no-files-found: error
  publish:
    name: Publish a release
    runs-on: "ubuntu-18.04"
    needs:
      - pack
    steps:
      - name: Get our distributables
        uses: actions/download-artifact@v2
        with:
          name: executeable
          path: exe

      - name: Upload server release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '**/*.exe'
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
